/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post124, git sha1 b5170e139) */

(* top =  1  *)
(* src = "C:\\Users\\mikea\\OneDrive\\Desktop\\Projects\\openTTDOOM\\hdl\\sequential.py:119" *)
(* generator = "Amaranth" *)
module counter(clk, rst, q, en);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [2:0] \$1 ;
  reg [1:0] \$2 ;
  (* src = "C:\\Users\\mikea\\AppData\\Roaming\\Python\\Python312\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mikea\\OneDrive\\Desktop\\Projects\\openTTDOOM\\hdl\\sequential.py:115" *)
  input en;
  wire en;
  (* src = "C:\\Users\\mikea\\OneDrive\\Desktop\\Projects\\openTTDOOM\\hdl\\sequential.py:116" *)
  output [1:0] q;
  reg [1:0] q = 2'h0;
  (* src = "C:\\Users\\mikea\\AppData\\Roaming\\Python\\Python312\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  assign \$1  = q + (* src = "C:\\Users\\mikea\\OneDrive\\Desktop\\Projects\\openTTDOOM\\hdl\\sequential.py:121" *) 1'h1;
  (* src = "C:\\Users\\mikea\\OneDrive\\Desktop\\Projects\\openTTDOOM\\hdl\\sequential.py:116" *)
  always @(posedge clk)
    q <= \$2 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$2  = q;
    if (en) begin
      \$2  = \$1 [1:0];
    end
    if (rst) begin
      \$2  = 2'h0;
    end
  end
endmodule
